spring:
  datasource:
    url: jdbc:mysql://localhost:3000/tacocloud
    username: tacouser
    password: tacopassword
  jpa:
    open-in-view: false

taco:
  orders:
    pageSize: 10

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3000/tacocloud
    username: tacouser
    password: tacopassword

logging:
  level:
    taco: debug